# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0004_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
